apiVersion: v2
name: pixelfed
version: v3.8.2
description: Helm chart to deploy Pixelfed
appVersion: 0.12.5
dependencies:
  - name: valkey
    version: "0.8.0"
    repository: "https://valkey.io/valkey-helm/"
    condition: valkey.internal
