apiVersion: v2
name: pixelfed
version: v3.8.2
description: Helm chart to deploy Pixelfed
appVersion: 0.12.5
dependencies:
  - name: redis
    version: "23.2.1"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.internal
